services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        restart: always
        ports:
            - "40110:1433"
        environment:
            SA_PASSWORD: "leane"
            ACCEPT_EULA: "Y"
        volumes:
            - sqlserver_data:/var/opt/mssql
        networks:
            - app_network

    nodeapp:
        build: .
        container_name: nodeapp
        restart: always
        ports:
            - "8080:3000"
        environment:
            NODE_END: "dev"
            DB_HOST: "sqlserver"
            DB_PORT: "1433"
            DB_USER: "sa"
            DB_PASSWORD: "leane"
            DB_NAME: "running_shop"
        depends_on:
            - sqlserver
        networks:
            - app_network

volumes:
    sqlserver_data:

networks:
    app_network:
        driver: bridge
